openapi: 3.0.0
info:
  title: Pets API
  version: 1.0.0
  description: API para gestionar mascotas
servers:
  - url: http://localhost:3000/api/pets
paths:
  /:
    get:
      summary: Obtiene todas las mascotas
      tags:
        - Pets
      responses:
        '200':
          description: Lista de mascotas
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        specie:
                          type: string
                        birthDate:
                          type: string
    post:
      summary: Crea una nueva mascota
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                specie:
                  type: string
                birthDate:
                  type: string
      responses:
        '200':
          description: Mascota creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      specie:
                        type: string
                      birthDate:
                        type: string
  /withimage:
    post:
      summary: Crea una nueva mascota con imagen
      tags:
        - Pets
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                specie:
                  type: string
                birthDate:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Mascota creada con imagen exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      specie:
                        type: string
                      birthDate:
                        type: string
                      image:
                        type: string
  /{pid}:
    put:
      summary: Actualiza una mascota por ID
      tags:
        - Pets
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID de la mascota
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Mascota actualizada exitosamente
    delete:
      summary: Elimina una mascota por ID
      tags:
        - Pets
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID de la mascota
      responses:
        '200':
          description: Mascota eliminada exitosamente
